apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - image: citizenstig/httpbin
        imagePullPolicy: Always
        name: httpbin
        ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: httpbin